source 'https://github.com/CocoaPods/Specs.git'

target 'YSMRequestMappingExtend', :exclusive => true do
  pod "YSMRequestMappingExtend", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "YSMRequestMappingExtend", :path => "../"

pod 'AFNetworking', '~> 2.3.1'
pod 'RestKit/ObjectMapping', '~> 0.23.3'
  
end
